version: '3'
services:
  webapp:
    build:
      context: docker
      dockerfile: Dockerfile
    restart: 'no'
    ports:
      - '8018:80'
    volumes:
      - './:/var/www/'
      - './docker/app/app.conf:/etc/apache2/sites-available/000-default.conf'
      - './docker/php/php.ini:/etc/php/8.1/apache2/php.ini'
      - './docker/php/php.ini:/etc/php/8.1/cli/php.ini'
    links:
      - mariadb
      - mailhog
  mariadb:
    image: 'mariadb:10.3.28'
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - /var/lib/mysql
  adminer:
    image: adminer
    restart: 'no'
    links:
      - mariadb
    ports:
      - '8019:8080'
  mailhog:
    image: mailhog/mailhog
    restart: 'no'
    ports:
      - '1035:1025'
      - '8031:8025'
